namespace: timhatdiehandandermaus

deployment:
  name: preliminary-frontend
  image: ghcr.io/ghcr.io/tim-hat-die-hand-an-der-maus/preliminary-frontend:__TAG__
  imagePullPolicy: Always
  revisionHistoryLimit: 1
  ports:
  - 80
  replicas: 1
  labels:
    app: preliminary-frontend
  requests:
    cpu: 50m
    memory: 20Mi

service:
  name: preliminary-frontend
  port: 80
  targetPort: 80
  appSelector: preliminary-frontend

ingress:
  hosts:
    - timhatdiehandandermaus.consulting
  secret: tls-preliminary-frontend
  issuer: letsencrypt-issuer-http
  name: preliminary-frontend
